[package]
name = "shutter"
version = "0.1.0"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.25.3", features = ["serde-serialize", "sparse"] }
simba="0.4.0"
num-traits = "0.2.14"
serde = { version="1.0.111", features=["derive"] }
#opencv = { version = "0.49.0", features = ["contrib", "opencv-4"]}
opencv = { version = "0.53.0" }
volta =  { path = "../volta", features = ["ipp", "mkl", "gsl"] }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-app = { git = "https://github.com/sdroege/gstreamer-rs" }
gstreamer-base = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-video = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-gl = { git = "https://github.com/sdroege/gstreamer-rs" }
glib = { git = "https://github.com/gtk-rs/gtk-rs"}
# gio = { git = "https://github.com/gtk-rs/gtk-rs"}
# gdk = { git = "https://github.com/gtk-rs/gtk-rs"}
anyhow = "1.0.38"
once_cell = "1.5.2"
lazy_static = "1.0"
structopt = "0.3"
# resize = "0.7.2"
# kmeans_colors = "0.4.0"
# edge-detection = "0.2.5"
# image-conv = "0.3.0"

[features]
mkl=[]
gsl=[]
ipp=[]
opencvlib=[]
vlfeatlib=[]
processor=[]
