[package]
name = "shutter"
version = "0.0.1"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"
license = "MIT"
keywords = ["image"]
categories = ["science"]
build = "build.rs"
publish = ["crates-io"]
readme = "README.md"
description = "Image processing data structures and algorithms"

[dependencies]
nalgebra = { version = "0.29.0", features = ["serde-serialize", "sparse"] }
simba={ version="0.6.0", features=["wide"] }
num-traits = "0.2.14"
serde = { version="1.0.111", features=["derive"] }
opencv = "0.53.0"
gstreamer = "0.17.0"
gstreamer-app = "0.17.0"
gstreamer-base = "0.17.0"
gstreamer-video = "0.17.0"
gstreamer-gl = "0.17.0"
glib = "0.14.2"
anyhow = "1.0.38"
once_cell = "1.5.2"
lazy_static = "1.0"
structopt = "0.3"
ripple = { path = "../ripple" }
away = { path = "../away" }

[features]
mkl=[]
gsl=[]
ipp=[]
opencvlib=[]
vlfeatlib=[]
processor=[]
