[package]
name = "shutter"
version = "0.1.0"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"
license = "MIT"
keywords = ["image"]
categories = ["science"]
build = "build.rs"
publish = ["crates-io"]
readme = "README.md"
description = "Image processing data structures and algorithms"

[dependencies]
nalgebra = { version = "0.28.0", features = ["serde-serialize", "sparse"] }
simba="0.5.1"
num-traits = "0.2.14"
serde = { version="1.0.111", features=["derive"] }
opencv = "0.53.0"
volta =  { path = "../volta", features = ["ipp", "mkl", "gsl"] }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-app = { git = "https://github.com/sdroege/gstreamer-rs" }
gstreamer-base = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-video = { git = "https://github.com/sdroege/gstreamer-rs"  }
gstreamer-gl = { git = "https://github.com/sdroege/gstreamer-rs" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
anyhow = "1.0.38"
once_cell = "1.5.2"
lazy_static = "1.0"
structopt = "0.3"

[features]
mkl=[]
gsl=[]
ipp=[]
opencvlib=[]
vlfeatlib=[]
processor=[]
