/* automatically generated by rust-bindgen 0.57.0 */

pub type Ipp8u = ::std::os::raw::c_uchar;
pub type Ipp16u = ::std::os::raw::c_ushort;
pub type Ipp16s = ::std::os::raw::c_short;
pub type Ipp32f = f32;
pub const IppChannels_ippC0: IppChannels = 0;
pub const IppChannels_ippC1: IppChannels = 1;
pub const IppChannels_ippC2: IppChannels = 2;
pub const IppChannels_ippC3: IppChannels = 3;
pub const IppChannels_ippC4: IppChannels = 4;
pub const IppChannels_ippP2: IppChannels = 5;
pub const IppChannels_ippP3: IppChannels = 6;
pub const IppChannels_ippP4: IppChannels = 7;
pub const IppChannels_ippAC1: IppChannels = 8;
pub const IppChannels_ippAC4: IppChannels = 9;
pub const IppChannels_ippA0C4: IppChannels = 10;
pub const IppChannels_ippAP4: IppChannels = 11;
pub type IppChannels = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IppiSize {
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_IppiSize() {
    assert_eq!(
        ::std::mem::size_of::<IppiSize>(),
        8usize,
        concat!("Size of: ", stringify!(IppiSize))
    );
    assert_eq!(
        ::std::mem::align_of::<IppiSize>(),
        4usize,
        concat!("Alignment of ", stringify!(IppiSize))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<IppiSize>())).width as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(IppiSize),
            "::",
            stringify!(width)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<IppiSize>())).height as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(IppiSize),
            "::",
            stringify!(height)
        )
    );
}
pub const IppiDitherType_ippDitherNone: IppiDitherType = 0;
pub const IppiDitherType_ippDitherFS: IppiDitherType = 1;
pub const IppiDitherType_ippDitherJJN: IppiDitherType = 2;
pub const IppiDitherType_ippDitherStucki: IppiDitherType = 3;
pub const IppiDitherType_ippDitherBayer: IppiDitherType = 4;
pub type IppiDitherType = ::std::os::raw::c_uint;
pub type IppStatus = ::std::os::raw::c_int;
extern "C" {
    pub fn ippiReduceBits_8u1u_C1R(
        pSrc: *const Ipp8u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        dstBitOffset: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        seed: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        threshold: Ipp8u,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_8u_C1R(
        pSrc: *const Ipp8u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_8u_C3R(
        pSrc: *const Ipp8u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_8u_C4R(
        pSrc: *const Ipp8u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_8u_AC4R(
        pSrc: *const Ipp8u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u_C1R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u_C3R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u_C4R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u_AC4R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u8u_C1R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u8u_C3R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u8u_C4R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16u8u_AC4R(
        pSrc: *const Ipp16u,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s_C1R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s_C3R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s_C4R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s_AC4R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s8u_C1R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s8u_C3R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s8u_C4R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_16s8u_AC4R(
        pSrc: *const Ipp16s,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f8u_C1R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f8u_C3R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f8u_C4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f8u_AC4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp8u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16u_C1R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16u_C3R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16u_C4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16u_AC4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16u,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16s_C1R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16s_C3R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16s_C4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBits_32f16s_AC4R(
        pSrc: *const Ipp32f,
        srcStep: ::std::os::raw::c_int,
        pDst: *mut Ipp16s,
        dstStep: ::std::os::raw::c_int,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        levels: ::std::os::raw::c_int,
        pBuffer: *mut Ipp8u,
    ) -> IppStatus;
}
extern "C" {
    pub fn ippiReduceBitsGetBufferSize(
        ippChan: IppChannels,
        roiSize: IppiSize,
        noise: ::std::os::raw::c_int,
        dtype: IppiDitherType,
        pBufferSize: *mut ::std::os::raw::c_int,
    ) -> IppStatus;
}
